#!/bin/bash

for k in `seq 2 15`;
do
    sbatch --job-name=stoch_case14_$k --output=./output/stoch_case14_$k.out ./runscript.sh ../data/nesta_case14_ieee_nk.m $k
done

for k in `seq 2 15`;
do
    sbatch --job-name=stoch_case24_$k --output=./output/stoch_case24_$k.out ./runscript.sh ../data/nesta_case24_ieee_rts_nk.m $k
done

for k in `seq 2 15`;
do
    sbatch --job-name=stoch_case73_$k --output=./output/stoch_case73_$k.out ./runscript.sh ../data/nesta_case73_ieee_rts_nk.m $k
done

